"""Extract the A-SPX numeric tables to committed Python.

WHAT AND FROM WHERE
-------------------
A-SPX (clause 5.7) needs three static numeric facts:

  * ``sbg_template_highres`` / ``sbg_template_lowres`` -- the master subband
    group templates of clause 5.7.6.3.1.1, printed in the Part 1 PDF.
  * ``QWIN`` -- the 640-tap 64-band QMF prototype of Annex D.3, shipped as a
    float array in the official ``ts_103190_tables.c``.
  * ``ASPX_NOISE`` -- the 512 complex unit-magnitude noise values of Annex D.2,
    also in that C file.

The templates are parsed from the PDF by their own caption lines; the two
numeric arrays come from the standards body's machine-readable C file (the same
source Annex A.0 names for the Huffman codebooks).  Neither the PDF nor the .c
file is committed or read at runtime; this tool emits
``ac4bindings/ac4bindings/aspx_tables.py`` once.

GATES
-----
  * both templates strictly increasing and starting/ending on an even QMF
    subband (clause 5.7.6.3.1.1's own shape claim);
  * the high-resolution template spans QMF 18..62 and the low one 10..46,
    the exact ranges clause 5.7.6.3.1.1 states;
  * ``QWIN`` is 640 taps and its magnitude is symmetric about index 320, the
    MPEG prototype shape (its signs are folded, so |w| not w is symmetric);
  * ``ASPX_NOISE`` is 512 entries of unit magnitude (clause 5.7.6.4.2).

Usage:
    python tools/extract_ac4_aspx_tables.py [--pdf PATH] [--src PATH] [--write]
"""

from __future__ import annotations

import argparse
import os
import re
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "ac4bindings", "aspx_tables.py")

_DEFAULT_PDF = os.path.join(
    os.path.dirname(os.path.dirname(HERE)), "spec",
    "ts_10319001v010301p.pdf")
_DEFAULT_C = os.path.join(
    os.path.dirname(os.path.dirname(HERE)), "spec", "ts_103190_tables.c")

N_QWIN = 640
N_NOISE = 512


def _templates_from_pdf(pdf_path):
    import pymupdf
    doc = pymupdf.open(pdf_path)
    text = "\n".join(page.get_text() for page in doc)
    out = {}
    for name in ("sbg_template_lowres", "sbg_template_highres"):
        # The PDF renders the array delimiters as PUA glyphs \x05..\x06, not
        # ASCII brackets, so the body runs to the closing \x06.
        m = re.search(rf"{name}\s*=\s*\x05([^\x06]+)\x06", text)
        if not m:
            raise SystemExit(f"{name} not found in PDF")
        out[name] = [int(x) for x in re.findall(r"\d+", m.group(1))]
    return out


def _array_from_c(src_path, name, declared, dim2=None):
    src = open(src_path, encoding="utf-8", errors="replace").read()
    src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
    dim = r"\s*\[\s*\d+\s*\]" + (r"\s*\[\s*\d+\s*\]" if dim2 else "")
    start = re.search(rf"const\s+\w+\s+{name}\s*{dim}\s*=\s*\{{", src)
    if not start:
        raise SystemExit(f"{name} not found in {src_path}")
    # Take the outermost brace: for a 2-D array the body contains braces, so a
    # non-greedy match would stop at the first inner ``}``.
    depth, i = 0, start.end() - 1
    for j in range(i, len(src)):
        if src[j] == "{":
            depth += 1
        elif src[j] == "}":
            depth -= 1
            if depth == 0:
                break
    body = src[i + 1:j]
    vals = [float(x) for x in
            re.findall(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", body)]
    if len(vals) != declared:
        raise SystemExit(f"{name}: parsed {len(vals)}, expected {declared}")
    return vals


def gate(tpl, qwin, noise):
    hi, lo = tpl["sbg_template_highres"], tpl["sbg_template_lowres"]
    assert all(hi[i] < hi[i + 1] for i in range(len(hi) - 1))
    assert all(lo[i] < lo[i + 1] for i in range(len(lo) - 1))
    assert hi[0] % 2 == 0 and hi[-1] % 2 == 0
    assert lo[0] % 2 == 0 and lo[-1] % 2 == 0
    assert (hi[0], hi[-1]) == (18, 62), (hi[0], hi[-1])
    assert (lo[0], lo[-1]) == (10, 46), (lo[0], lo[-1])
    assert len(qwin) == N_QWIN
    w = np.asarray(qwin)
    assert np.allclose(np.abs(w[1:]), np.abs(w[1:])[::-1], atol=1e-9)
    assert len(noise) == 2 * N_NOISE
    n = np.asarray(noise, float).reshape(-1, 2)
    mag = np.hypot(n[:, 0], n[:, 1])
    assert np.allclose(mag, 1.0, atol=1e-6), (mag.min(), mag.max())


_HEADER = '''"""A-SPX static tables (ETSI TS 103 190-1 clauses 5.7.6.3.1.1 and D.2/D.3).

GENERATED by ``tools/extract_ac4_aspx_tables.py --write`` and committed.  The
subband group templates are read from the specification PDF; ``QWIN`` and
``ASPX_NOISE`` come from the official ``ts_103190_tables.c`` (the machine
readable source Annex A.0 names).  Neither the PDF nor the .c file is shipped
or read at runtime.

``QWIN`` is the 640-tap 64-band QMF prototype; ``ASPX_NOISE_RE`` /
``ASPX_NOISE_IM`` are the 512 unit-magnitude complex values the HF envelope
adjuster injects as noise.
"""

#: Master subband group templates, clause 5.7.6.3.1.1 (QMF subband borders).
SBG_TEMPLATE_HIGHRES = %(highres)r
SBG_TEMPLATE_LOWRES = %(lowres)r

#: 64-band QMF prototype window, Annex D.3 (640 taps).
QWIN = %(qwin)r

#: Adaptive noise values, Annex D.2 (512 unit-magnitude complex entries).
ASPX_NOISE_RE = %(noise_re)r
ASPX_NOISE_IM = %(noise_im)r

SOURCE = ("ETSI TS 103 190-1 V1.3.1 (2018-02), clause 5.7.6.3.1.1 "
          "(templates), Annex D.2/D.3 (QWIN, ASPX_NOISE)")
'''


def write_module(tpl, qwin, noise):
    n = np.asarray(noise, float).reshape(-1, 2)
    text = _HEADER % {
        "highres": tpl["sbg_template_highres"],
        "lowres": tpl["sbg_template_lowres"],
        "qwin": [float(x) for x in qwin],
        "noise_re": [float(x) for x in n[:, 0]],
        "noise_im": [float(x) for x in n[:, 1]],
    }
    with open(OUT, "w") as f:
        f.write(text)
    return OUT


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--pdf", default=_DEFAULT_PDF)
    ap.add_argument("--src", default=_DEFAULT_C)
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args(argv)

    tpl = _templates_from_pdf(a.pdf)
    print("templates:", {k: len(v) for k, v in tpl.items()})
    qwin = _array_from_c(a.src, "QWIN", N_QWIN)
    noise = _array_from_c(a.src, "ASPX_NOISE", 2 * N_NOISE, dim2=True)
    gate(tpl, qwin, noise)
    print("gates passed")
    if a.write:
        print("wrote", write_module(tpl, qwin, noise))
    return 0


if __name__ == "__main__":
    sys.exit(main())
