"""Extract the AC-4 Huffman codebook tables from the official ETSI table file.

WHY THIS SOURCE
---------------
ETSI TS 103 190-1 Annex A does not print the Huffman arrays in the PDF.  It
says, in A.0: *"All Huffman codebook tables are available in the file
ts_103190_tables.c contained in archive ts_10319001v010301p0.zip which
accompanies the present document.  Each Huffman table consists of a sub-table
containing length values and another sub-table containing the codeword."*

So the authoritative machine-readable source is the standards body's own C
file, published alongside the specification.  This tool parses that file and
emits committed Python (``ac4bindings/ac4bindings/huffman.py``); the .c file
and the .zip are never shipped and never read at runtime, exactly as
``atsc3lib`` ships its A/322 numeric tables in code.

The codeword semantics are the spec's (clause 4.2.8.5): a codeword is a
canonical Huffman prefix read MSB-first; ``LEN[i]`` is its bit length and
``CW[i]`` its value.  Decoding builds a lookup from (length, codeword) -> index.

Usage:
    python tools/extract_ac4_huffman.py --src /path/to/ts_103190_tables.c --write
"""

from __future__ import annotations

import argparse
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "ac4bindings", "huffman.py")

_ARRAY = re.compile(
    r"const\s+(?:int|int32|unsigned int|uint32_t)\s+"
    r"([A-Z0-9_]+)\s*\[\s*(\d+)\s*\]\s*=\s*\{(.*?)\}\s*;",
    re.DOTALL)

#: Arrays the ASF (channel) decode path needs.  A-SPX / A-CPL / metadata
#: codebooks are large and land with those rungs; this keeps the committed
#: module to what is actually used.
ASF_ARRAYS = (
    ["ASF_HCB_SCALEFAC_LEN", "ASF_HCB_SCALEFAC_CW"]
    + [f"ASF_HCB_{n}_{kind}" for n in range(1, 12)
       for kind in ("LEN", "CW")]
    + ["ASF_HCB_SNF_LEN", "ASF_HCB_SNF_CW"]
)


def parse_arrays(text: str):
    """-> {name: [int, ...]} for every array in the ETSI C file."""
    out = {}
    for m in _ARRAY.finditer(text):
        name, count, body = m.group(1), int(m.group(2)), m.group(3)
        body = re.sub(r"/\*.*?\*/", "", body, flags=re.DOTALL)
        body = re.sub(r"//[^\n]*", "", body)
        values = []
        for token in body.replace("\n", " ").split(","):
            token = token.strip()
            if not token:
                continue
            values.append(int(token, 0))
        if len(values) != count:
            raise SystemExit(
                f"{name}: declared {count}, parsed {len(values)}")
        out[name] = values
    return out


def gate(arrays):
    """Gates that a mis-parsed table fails."""
    # Every LEN/CW pair agrees in length.
    for name in arrays:
        if name.endswith("_LEN"):
            cw = name[:-4] + "_CW"
            assert cw in arrays, f"missing {cw}"
            assert len(arrays[name]) == len(arrays[cw]), name
    # A canonical prefix code: Kraft sum == 1 for each complete codebook.
    for name, lens in arrays.items():
        if not name.endswith("_LEN"):
            continue
        # codebooks may be incomplete; only check the full ones
        kraft = sum(2.0 ** (-n) for n in lens)
        assert kraft <= 1.0 + 1e-9, (name, kraft)
    # The spectrum codebooks 1..11 have the sizes the spec's Table A.2+ states.
    assert len(arrays["ASF_HCB_1_LEN"]) == 81
    assert len(arrays["ASF_HCB_SCALEFAC_LEN"]) == 121


def write_module(arrays):
    lines = [
        '"""AC-4 Huffman codebook tables (ETSI TS 103 190-1 Annex A).',
        "",
        "GENERATED by ``tools/extract_ac4_huffman.py --write`` from the official",
        "``ts_103190_tables.c`` published alongside the specification (Annex A.0",
        "names that file as the machine-readable source).  Committed; the .c file",
        "is never shipped and never read at runtime.",
        "",
        "``*_LEN[i]`` is the bit length of codeword ``i`` and ``*_CW[i]`` its",
        "value; decoding is a canonical prefix read MSB-first (clause 4.2.8.5).",
        '"""',
        "",
    ]
    for name in sorted(arrays):
        vals = arrays[name]
        lines.append(f"{name} = {vals!r}")
    lines.append("")
    lines.append('SOURCE = ("ETSI TS 103 190-1 V1.3.1 (2018-02) Annex A; '
                 'ts_103190_tables.c")')
    lines.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    return OUT


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True,
                    help="path to ts_103190_tables.c from the ETSI archive")
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args(argv)

    arrays = parse_arrays(open(a.src).read())
    print(f"parsed {len(arrays)} arrays from {a.src}")
    gate(arrays)
    print("gates passed")
    if a.write:
        path = write_module(arrays)
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
