"""Emit ac4bindings/ac4bindings/tables.py from the extracted spec tables.

Kept separate from the extractor so the numeric reading and the file writing
can be tested independently, and so the emitted module is a plain data file
with no PyMuPDF import.
"""

from __future__ import annotations

import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "ac4bindings", "tables.py")

_HEADER = '''"""AC-4 numeric tables (ETSI TS 103 190-1 Annex B).

GENERATED by ``tools/extract_ac4_tables.py --write`` and committed.  The
specification PDF is never shipped and never read at runtime; these are the
numeric facts, extracted once and gated against the standard's own Table B.1
(``num_sfb`` per transform length), exactly as ``atsc3lib`` ships its A/322
tables.

The scale factor band offsets are the table the reference receiver documents
as having been silently contaminated once (rows 40..55 sit at the top of the
next page, above Table B.5's restarting sfb column); the Table B.1 gate is what
catches that class of error.
"""

#: Number of scale factor bands per transform length, 44.1/48 kHz (Table B.1).
NUM_SFB = %(num_sfb)r

#: Scale factor band offsets per transform length @ 48 kHz (Tables B.4..B.7).
#: ``SFB_OFFSET[length][NUM_SFB[length]] == length``.
SFB_OFFSET = %(offsets)r

#: Huffman spectrum codebook metadata (Tables A.2..A.12): the decode radix and
#: offset used by pseudocode 19, and the dimension/signedness (A.14/A.15).
CB_MOD = %(cb_mod)r
CB_OFF = %(cb_off)r
CB_DIM = %(cb_dim)r
UNSIGNED_CB = %(unsigned)r

SOURCE = ("ETSI TS 103 190-1 V1.3.1 (2018-02), Annex A (codebooks), "
          "Annex B (scale factor bands)")
'''


def write_tables(offsets_by_length, num_sfb, cb_meta):
    cb_mod = {cb: m["mod"] for cb, m in cb_meta.items()}
    cb_off = {cb: m["off"] for cb, m in cb_meta.items()}
    from extract_ac4_tables import CB_DIM, UNSIGNED_CB
    text = _HEADER % {"num_sfb": dict(sorted(num_sfb.items())),
                      "offsets": dict(sorted(offsets_by_length.items())),
                      "cb_mod": cb_mod, "cb_off": cb_off,
                      "cb_dim": CB_DIM, "unsigned": UNSIGNED_CB}
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(text)
    return OUT
