# Generated by Django 5.2.17 on 2026-10-05 03:18

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.CharField(default='system', max_length=150)),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Broadcaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('bsids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.CharField(max_length=512)),
                ('ref', models.CharField(blank=True, max_length=128)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=64, unique=True)),
                ('subject_dn', models.CharField(max_length=512)),
                ('common_name', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('organizational_unit', models.CharField(blank=True, max_length=255)),
                ('profile', models.CharField(choices=[('root', 'Root CA (A/360 5.3.1.2)'), ('issuing-ca', 'Issuing CA (A/360 5.3.1.3)'), ('signaling-signer', 'Broadcast signaling signer (A/360 5.3.1.6)'), ('cdt-signer', 'CertificationData signer (A/360 5.2.2.2)'), ('ocsp-responder', 'OCSP responder (A/360 5.3.1.7)')], max_length=32)),
                ('not_before', models.DateTimeField()),
                ('not_after', models.DateTimeField()),
                ('der_file', models.CharField(max_length=1024)),
                ('ski', models.CharField(db_index=True, max_length=64)),
                ('aki', models.CharField(blank=True, max_length=64)),
                ('bsids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('eku', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('key_path', models.CharField(blank=True, max_length=1024)),
                ('key_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('good', 'Good'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('superseded', 'Superseded by rollover')], db_index=True, default='good', max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broadcaster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='catalog.broadcaster')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.certificate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OcspResponder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255)),
                ('key_path', models.CharField(max_length=1024)),
                ('key_sha256', models.CharField(blank=True, max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_responder', to='catalog.certificate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OcspResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('good', 'Good'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('superseded', 'Superseded by rollover')], default='good', max_length=16)),
                ('produced_at', models.DateTimeField()),
                ('this_update', models.DateTimeField(blank=True, null=True)),
                ('next_update', models.DateTimeField(blank=True, null=True)),
                ('der_file', models.CharField(max_length=1024)),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocsp_responses', to='catalog.certificate')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.certificate')),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='catalog.ocspresponder')),
            ],
            options={
                'ordering': ['-produced_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishedSignaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signing_time', models.DateTimeField()),
                ('cdt_file', models.CharField(blank=True, max_length=1024)),
                ('smt_file', models.CharField(blank=True, max_length=1024)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published', to='catalog.broadcaster')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.certificate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RolloverPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_from', models.DateTimeField()),
                ('current_until', models.DateTimeField()),
                ('state', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active (window open)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broadcaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollovers', to='catalog.broadcaster')),
                ('current', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_current', to='catalog.certificate')),
                ('next', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_next', to='catalog.certificate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(condition=models.Q(('not_after__gt', models.F('not_before'))), name='cert_validity_ordered'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['good', 'revoked', 'expired', 'superseded'])), name='cert_status_known'),
        ),
        migrations.AddIndex(
            model_name='ocspresponse',
            index=models.Index(fields=['certificate', '-produced_at'], name='catalog_ocs_certifi_924398_idx'),
        ),
        migrations.AddConstraint(
            model_name='rolloverplan',
            constraint=models.CheckConstraint(condition=models.Q(('current_until__gte', models.F('next_from'))), name='rollover_window_ordered'),
        ),
    ]
